In [3]:
import numpy as np
np.set_printoptions(threshold=50, linewidth=50)
from datascience import *

In [4]:
url = 'http://www.census.gov/popest/data/national/asrh/2014/files/NC-EST2014-AGESEX-RES.csv'
full = Table.read_table(url)
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014
0    | 0    | 3944153       | 3944160           | 3951330         | 3963071         | 3926665         | 3945610         | 3948350
0    | 1    | 3978070       | 3978090           | 3957888         | 3966510         | 3978006         | 3943077         | 3962123
0    | 2    | 4096929       | 4096939           | 4090862         | 3971573         | 3979952         | 3992690         | 3957772
0    | 3    | 4119040       | 4119051           | 4111920         | 4102501         | 3983049         | 3992425         | 4005190
0    | 4    | 4063170       | 4063186           | 4077552         | 4122303         | 4112638         | 3994047         | 4003448
0    | 5    | 4056858       | 4056872           | 4064653         | 4087713         | 4132210         | 4123408         | 4004858
0    | 6    | 4066381       | 4066412           | 4073013         | 4074979         | 4097780         | 4143094         | 4134352
0    | 7    | 4030579       | 4030594           | 4043047         | 4083240         | 4084964         | 4108615         | 4154000
0    | 8    | 4046486       | 4046497           | 4025604         | 4053206         | 4093213         | 4095827         | 4119524
0    | 9    | 4148353       | 4148369           | 4125415         | 4035769         | 4063193         | 4104133         | 4106832
... (296 rows omitted)

In [5]:
partial = full.select(['SEX', 'AGE', 4, 8])
partial

SEX  | AGE  | POPESTIMATE2010 | POPESTIMATE2014
0    | 0    | 3951330         | 3948350
0    | 1    | 3957888         | 3962123
0    | 2    | 4090862         | 3957772
0    | 3    | 4111920         | 4005190
0    | 4    | 4077552         | 4003448
0    | 5    | 4064653         | 4004858
0    | 6    | 4073013         | 4134352
0    | 7    | 4043047         | 4154000
0    | 8    | 4025604         | 4119524
0    | 9    | 4125415         | 4106832
... (296 rows omitted)

In [6]:
simple = partial.relabeled('POPESTIMATE2010', '2010').relabeled(3, '2014')
simple

SEX  | AGE  | 2010    | 2014
0    | 0    | 3951330 | 3948350
0    | 1    | 3957888 | 3962123
0    | 2    | 4090862 | 3957772
0    | 3    | 4111920 | 4005190
0    | 4    | 4077552 | 4003448
0    | 5    | 4064653 | 4004858
0    | 6    | 4073013 | 4134352
0    | 7    | 4043047 | 4154000
0    | 8    | 4025604 | 4119524
0    | 9    | 4125415 | 4106832
... (296 rows omitted)

In [8]:
census = simple.with_columns([
        'Change', simple.column(3) - simple.column(2), 
        'Growth', (simple.column(3) / simple.column(2)) ** (1/4) - 1])
census

SEX  | AGE  | 2010    | 2014    | Change  | Growth
0    | 0    | 3951330 | 3948350 | -2980   | -0.000188597
0    | 1    | 3957888 | 3962123 | 4235    | 0.000267397
0    | 2    | 4090862 | 3957772 | -133090 | -0.00823453
0    | 3    | 4111920 | 4005190 | -106730 | -0.0065532
0    | 4    | 4077552 | 4003448 | -74104  | -0.00457471
0    | 5    | 4064653 | 4004858 | -59795  | -0.00369821
0    | 6    | 4073013 | 4134352 | 61339   | 0.00374389
0    | 7    | 4043047 | 4154000 | 110953  | 0.00679123
0    | 8    | 4025604 | 4119524 | 93920   | 0.00578232
0    | 9    | 4125415 | 4106832 | -18583  | -0.00112804
... (296 rows omitted)

In [9]:
census.set_format('Growth', PercentFormatter)
census.set_format([2, 3, 4], NumberFormatter)

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 0    | 3,951,330   | 3,948,350   | -2,980    | -0.02%
0    | 1    | 3,957,888   | 3,962,123   | 4,235     | 0.03%
0    | 2    | 4,090,862   | 3,957,772   | -133,090  | -0.82%
0    | 3    | 4,111,920   | 4,005,190   | -106,730  | -0.66%
0    | 4    | 4,077,552   | 4,003,448   | -74,104   | -0.46%
0    | 5    | 4,064,653   | 4,004,858   | -59,795   | -0.37%
0    | 6    | 4,073,013   | 4,134,352   | 61,339    | 0.37%
0    | 7    | 4,043,047   | 4,154,000   | 110,953   | 0.68%
0    | 8    | 4,025,604   | 4,119,524   | 93,920    | 0.58%
0    | 9    | 4,125,415   | 4,106,832   | -18,583   | -0.11%
... (296 rows omitted)

In [10]:
max(census.column(1))

999

In [11]:
totals = census.where('AGE', 999)
totals

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 999  | 309,347,057 | 318,857,056 | 9,509,999 | 0.76%
1    | 999  | 152,089,484 | 156,936,487 | 4,847,003 | 0.79%
2    | 999  | 157,257,573 | 161,920,569 | 4,662,996 | 0.73%

In [12]:
totals.group(1)

AGE  | count
999  | 3

In [13]:
totals.take([1, 2])

SEX  | AGE  | 2010        | 2014        | Change    | Growth
1    | 999  | 152,089,484 | 156,936,487 | 4,847,003 | 0.79%
2    | 999  | 157,257,573 | 161,920,569 | 4,662,996 | 0.73%

In [17]:
totals = census.where('AGE', 999)
totals

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 999  | 309,347,057 | 318,857,056 | 9,509,999 | 0.76%
1    | 999  | 152,089,484 | 156,936,487 | 4,847,003 | 0.79%
2    | 999  | 157,257,573 | 161,920,569 | 4,662,996 | 0.73%

In [18]:
totals = totals.drop(totals.take([1, 2]))

In [19]:
totals

In [20]:
totals = census.where('AGE', 999)
totals

SEX  | AGE  | 2010        | 2014        | Change    | Growth
0    | 999  | 309,347,057 | 318,857,056 | 9,509,999 | 0.76%
1    | 999  | 152,089,484 | 156,936,487 | 4,847,003 | 0.79%
2    | 999  | 157,257,573 | 161,920,569 | 4,662,996 | 0.73%

In [21]:
totals.drop(totals.take(2))

In [26]:
no_sums = census.where(np.logical_and(census.column('AGE') < 999,
                                      census.column('SEX') > 0))
no_sums.show()
#pivoted = no_sums.pivot('SEX', 'AGE', '2014', sum)

In [28]:
no_sums.pivot('SEX', 'AGE', '2014',sum)

AGE  | 1       | 2
0    | 2017857 | 1930493
1    | 2023253 | 1938870
2    | 2022502 | 1935270
3    | 2048618 | 1956572
4    | 2043498 | 1959950
5    | 2043467 | 1961391
6    | 2110328 | 2024024
7    | 2122240 | 2031760
8    | 2105122 | 2014402
9    | 2097272 | 2009560
... (91 rows omitted)